@apiulr = http://localhost:8180/api

# =========================================
# USERS

### GET ALL USERS
GET {{apiulr}}/user

### GET USER BY ID
GET {{apiulr}}/user/2

### GET /
GET {{apiulr}}

### POST /
POST {{apiulr}}/user
Content-Type: application/json

{
    "name":"Jony Marco",
    "email":"jonymarco@teste.com",
    "type":1,
    "password":123456
}

### UPDATE /
PUT {{apiulr}}/user/2
Content-Type: application/json

{
    "type":2
}

# =========================================
# TRANSACTIONS

### GET /
GET {{apiulr}}/transaction

### GET /
GET {{apiulr}}/transaction/4

### POST /
POST {{apiulr}}/transaction
Content-Type: application/json

{
    "payer_id":"16",
    "payee_id":"18",
    "amount":5000
}

### UPDATE /
PUT {{apiulr}}/transaction/4
Content-Type: application/json

{
    "confirmed":0
}

### TO CONFIRM /
PUT {{apiulr}}/transaction/confirmer/4
Content-Type: application/json

# =========================================
# WALLETS

### GET /
GET {{apiulr}}/wallet

### GET /
GET {{apiulr}}/wallet/10

### UPDATE /
PUT {{apiulr}}/wallet/11
Content-Type: application/json

{
    "amount":10000
}

# =========================================
# DOCUMENTS

### GET ALL DOCUMENTS
GET {{apiulr}}/document

### GET DOCUMENT BY ID
GET {{apiulr}}/document/1