@apiulr = http://localhost:8180/api

### GET ALL USERS
GET {{apiulr}}/user

### GET USER BY ID
GET {{apiulr}}/user/2

### GET /
GET {{apiulr}}

### POST /
POST {{apiulr}}/user
Content-Type: application/json

{
    "name":"Jony Marco",
    "email":"jonymarco@teste.com",
    "type":1,
    "password":123456
}

### UPDATE /
PUT {{apiulr}}/user/2
Content-Type: application/json

{
    "type":2
}

# =========================================
# TRANSACTIONS

### GET /
GET {{apiulr}}/transaction

### GET /
GET {{apiulr}}/transaction/1

### POST /
POST {{apiulr}}/transaction
Content-Type: application/json

{
    "payer_id":"2",
    "payee_id":"1",
    "amount":52032
}

### UPDATE /
PUT {{apiulr}}/transaction/1
Content-Type: application/json

{
    "confirmed":1
}

# =========================================
# WALLETS

### GET /
GET {{apiulr}}/wallet

### GET /
GET {{apiulr}}/wallet/1

### UPDATE /
PUT {{apiulr}}/wallet/2
Content-Type: application/json

{
    "amount":0
}
